stages:
  - test 
  - build
  - deploy

accounts-unit-test-job:
  image: python:3-bullseye
  stage: test
  script: 
    - cd accounts
    - pip install -r requirements.txt
    - python -m pytest

payments-unit-test-job:
  image: python:3-bullseye
  stage: test
  script: 
    - cd payments
    - pip install -r requirements.txt
    - python -m pytest

posts-unit-test-job:
  image: python:3-bullseye
  stage: test
  script: 
    - cd posts
    - pip install -r requirements.txt
    - python -m pytest

lint-job:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 accounts payments posts

build-front-end-job:
  stage: build
  image: node:lts-bullseye
  variables:
    PUBLIC_URL: https://404-team-not-found1.gitlab.io/go-food-me
  script:
    - cd ghi  # CHANGE THIS TO THE DIRECTORY THAT HAS package.json
    - npm install
    - npm run build
    - rm -rf public
    - cp build/index.html build/404.html  # Make this a SPA
  artifacts:
    paths:
      - ghi/build/  # Save all of the files in the build path
  
pages:  # THIS STEP MUST BE NAME PAGES
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
     # THE FIRST PART OF THIS COMMAND MUST BE THE DIRECTORY
     # THAT YOU cd INTO TO BUILD IT PLUS THE build/ AT THE
     # END
    - mv ghi/build/ public
  artifacts:
    paths:
      - public

build-accounts-api-image-job:  # RENAME THIS
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    # CHANGE THIS TO THE DIRECTORY THAT HAS YOUR Dockerfile
    - cd accounts

    # EVERYWHERE IT SHOWS fastapi_api BELOW, CHANGE THOSE
    # TO A MORE MEANINGFUL SERVICE NAME (5 PLACES)
    - docker build -t ${CI_REGISTRY_IMAGE}/accounts_api:latest .
    - docker tag ${CI_REGISTRY_IMAGE}/accounts_api:latest ${CI_REGISTRY_IMAGE}/accounts_api:$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/accounts_api:$CI_JOB_ID
    - docker push ${CI_REGISTRY_IMAGE}/accounts_api:latest

build-payments-api-image-job:  # RENAME THIS
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    # CHANGE THIS TO THE DIRECTORY THAT HAS YOUR Dockerfile
    - cd payments

    # EVERYWHERE IT SHOWS fastapi_api BELOW, CHANGE THOSE
    # TO A MORE MEANINGFUL SERVICE NAME (5 PLACES)
    - docker build -t ${CI_REGISTRY_IMAGE}/payments_api:latest .
    - docker tag ${CI_REGISTRY_IMAGE}/payments_api:latest ${CI_REGISTRY_IMAGE}/payments_api:$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/payments_api:$CI_JOB_ID
    - docker push ${CI_REGISTRY_IMAGE}/payments_api:latest

build-posts-api-image-job:  # RENAME THIS
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    # CHANGE THIS TO THE DIRECTORY THAT HAS YOUR Dockerfile
    - cd posts

    # EVERYWHERE IT SHOWS fastapi_api BELOW, CHANGE THOSE
    # TO A MORE MEANINGFUL SERVICE NAME (5 PLACES)
    - docker build -t ${CI_REGISTRY_IMAGE}/posts_api:latest .
    - docker tag ${CI_REGISTRY_IMAGE}/posts_api:latest ${CI_REGISTRY_IMAGE}/posts_api:$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/posts_api:$CI_JOB_ID
    - docker push ${CI_REGISTRY_IMAGE}/posts_api:latest

deploy-accounts-api-image-job:  # RENAME THIS
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: deploy
  image: docker:20.10.16
  needs:
    # CHANGE THIS TO THE JOB NAME FROM THE LAST STEP
    - build-accounts-api-image-job
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # EVERYWHERE IT SHOWS fastapi_api BELOW, CHANGE THOSE
    # TO THE NAME YOU CHOSE FOR THE BUILD STEP (2 PLACES)

    # EVERYWHERE IT SHOWS HEROKU_SERVICE_APP BELOW, CHANGE
    # THOSE TO THE VARIABLE NAME YOU CREATED FOR THE CI/CD
    # SETTINGS (2 PLACES)

    # IF THIS IS FOR A BACKGROUND SERVICE LIKE A POLLER,
    # CHANGE /web TO /worker (2 PLACES)
    - docker pull ${CI_REGISTRY_IMAGE}/accounts_api:latest
    - docker tag ${CI_REGISTRY_IMAGE}/accounts_api:latest registry.heroku.com/$HEROKU_ACCOUNTS_API_APP/web:latest
    - docker push registry.heroku.com/$HEROKU_ACCOUNTS_API_APP/web:latest

deploy-payments-api-image-job:  # RENAME THIS
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: deploy
  image: docker:20.10.16
  needs:
    # CHANGE THIS TO THE JOB NAME FROM THE LAST STEP
    - build-payments-api-image-job
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # EVERYWHERE IT SHOWS fastapi_api BELOW, CHANGE THOSE
    # TO THE NAME YOU CHOSE FOR THE BUILD STEP (2 PLACES)

    # EVERYWHERE IT SHOWS HEROKU_SERVICE_APP BELOW, CHANGE
    # THOSE TO THE VARIABLE NAME YOU CREATED FOR THE CI/CD
    # SETTINGS (2 PLACES)

    # IF THIS IS FOR A BACKGROUND SERVICE LIKE A POLLER,
    # CHANGE /web TO /worker (2 PLACES)
    - docker pull ${CI_REGISTRY_IMAGE}/payments_api:latest
    - docker tag ${CI_REGISTRY_IMAGE}/payments_api:latest registry.heroku.com/$HEROKU_PAYMENTS_API_APP/web:latest
    - docker push registry.heroku.com/$HEROKU_PAYMENTS_API_APP/web:latest

deploy-posts-api-image-job:  # RENAME THIS
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: deploy
  image: docker:20.10.16
  needs:
    # CHANGE THIS TO THE JOB NAME FROM THE LAST STEP
    - build-posts-api-image-job
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # EVERYWHERE IT SHOWS fastapi_api BELOW, CHANGE THOSE
    # TO THE NAME YOU CHOSE FOR THE BUILD STEP (2 PLACES)

    # EVERYWHERE IT SHOWS HEROKU_SERVICE_APP BELOW, CHANGE
    # THOSE TO THE VARIABLE NAME YOU CREATED FOR THE CI/CD
    # SETTINGS (2 PLACES)

    # IF THIS IS FOR A BACKGROUND SERVICE LIKE A POLLER,
    # CHANGE /web TO /worker (2 PLACES)
    - docker pull ${CI_REGISTRY_IMAGE}/posts_api:latest
    - docker tag ${CI_REGISTRY_IMAGE}/posts_api:latest registry.heroku.com/$HEROKU_POSTS_API_APP/web:latest
    - docker push registry.heroku.com/$HEROKU_POSTS_API_APP/web:latest

release-accounts-api-image-job:  # RENAME THIS
  stage: deploy
  image: node:10.17-alpine
  needs:
    # CHANGE THIS TO THE JOB NAME FROM THE LAST STEP
    - deploy-accounts-api-image-job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apk add curl bash
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    # EVERYWHERE IT SHOWS HEROKU_SERVICE_APP BELOW, CHANGE
    # THOSE TO THE VARIABLE NAME YOU CREATED FOR THE CI/CD
    # SETTINGS (1 PLACE)

    # IF THIS IS FOR A BACKGROUND SERVICE LIKE A POLLER,
    # CHANGE web TO worker (1 PLACE)
    - heroku container:release web --app $HEROKU_ACCOUNTS_API_APP

release-payments-api-image-job:  # RENAME THIS
  stage: deploy
  image: node:10.17-alpine
  needs:
    # CHANGE THIS TO THE JOB NAME FROM THE LAST STEP
    - deploy-payments-api-image-job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apk add curl bash
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    # EVERYWHERE IT SHOWS HEROKU_SERVICE_APP BELOW, CHANGE
    # THOSE TO THE VARIABLE NAME YOU CREATED FOR THE CI/CD
    # SETTINGS (1 PLACE)

    # IF THIS IS FOR A BACKGROUND SERVICE LIKE A POLLER,
    # CHANGE web TO worker (1 PLACE)
    - heroku container:release web --app $HEROKU_PAYMENTS_API_APP

release-posts-api-image-job:  # RENAME THIS
  stage: deploy
  image: node:10.17-alpine
  needs:
    # CHANGE THIS TO THE JOB NAME FROM THE LAST STEP
    - deploy-posts-api-image-job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apk add curl bash
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    # EVERYWHERE IT SHOWS HEROKU_SERVICE_APP BELOW, CHANGE
    # THOSE TO THE VARIABLE NAME YOU CREATED FOR THE CI/CD
    # SETTINGS (1 PLACE)

    # IF THIS IS FOR A BACKGROUND SERVICE LIKE A POLLER,
    # CHANGE web TO worker (1 PLACE)
    - heroku container:release web --app $HEROKU_POSTS_API_APP
