volumes:
    mongo-data:
        external: true
services:
    mongo:
        image: mongo:5
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
    fastapi-accounts:
        build:
            context: ./fastapi-accounts
            dockerfile: ./Dockerfile.dev
        ports:
            - "8000:8000"
        volumes:
            - ./fastapi-accounts:/app
        environment:
            DATABASE_URL: mongodb://root:password@mongo
            DATABASE_NAME: mongo-data
            WAIT_HOSTS: mongo:27017
    fastapi-payments:
        build:
            context: ./fastapi-payments
            dockerfile: ./Dockerfile.dev
        ports:
            - "8100:8000"
        volumes:
            - ./fastapi-payments:/app
        environment:
            DATABASE_URL: mongodb://root:password@mongo
            DATABASE_NAME: mongo-data
            WAIT_HOSTS: mongo:27017
    fastapi-posts:
        build:
            context: ./fastapi-posts
            dockerfile: ./Dockerfile.dev
        ports:
            - "8200:8000"
        volumes:
            - ./fastapi-posts:/app
        environment:
            DATABASE_URL: mongodb://root:password@mongo
            DATABASE_NAME: mongo-data
            WAIT_HOSTS: mongo:27017
    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./ghi:/app
        ports:
            - "3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            REACT_APP_FASTAPI_accounts: http://localhost:8000
            REACT_APP_FastAPI_payments: http://localhost:8100
            REACT_APP_FastAPI_posts: http://localhost:8200