volumes:
    postgres-data:
        external: true
services:
    postgres:
        build:
            context: ./relational-data
            dockerfile: ./Dockerfile.dev
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_MULTIPLE_DATABASES=accounts,payments,posts
            - POSTGRES_PASSWORD=test-databases
        ports:
            - 15432:5432
    fastapi-accounts:
        build:
            context: ./fastapi-accounts
            dockerfile: ./Dockerfile.dev
        ports:
            - "8000:8000"
        volumes:
            - ./fastapi-accounts:/app
        environment:
            DATABASE_URL: postgresql://admin:admin@postgres/accounts
            WAIT_HOSTS: postgres:5432
    fastapi-payments:
        build:
            context: ./fastapi-payments
            dockerfile: ./Dockerfile.dev
        ports:
            - "8100:8000"
        volumes:
            - ./fastapi-payments:/app
        environment:
            DATABASE_URL: postgresql://admin:admin@postgres/payments
            WAIT_HOSTS: postgres:5432
    fastapi-posts:
        build:
            context: ./fastapi-posts
            dockerfile: ./Dockerfile.dev
        ports:
            - "8200:8000"
        volumes:
            - ./fastapi-posts:/app
        environment:
            DATABASE_URL: postgresql://admin:admin@postgres/posts
            WAIT_HOSTS: postgres:5432
    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./ghi:/app
        ports:
            - "3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            REACT_APP_FASTAPI_accounts: http://localhost:8000
            REACT_APP_FastAPI_payments: http://localhost:8100
            REACT_APP_FastAPI_posts: http://localhost:8200