volumes:
    mongo-data:
        external: true
services:
    mongo:
        image: mongo:5
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - "27018:27017"
    accounts:
        build:
            context: ./accounts
            dockerfile: ./Dockerfile.dev
        ports:
            - "8000:8000"
        volumes:
            - ./accounts:/app
        environment:
            SIGNING_KEY: 26373b9ea24f7e169e921f89ef4591046241eba5e6c30af3709cf6aa5a711b40
            DATABASE_URL: mongodb://root:password@mongo
            DATABASE_NAME: mongo-data
            WAIT_HOSTS: mongo:27017
    payments:
        build:
            context: ./payments
            dockerfile: ./Dockerfile.dev
        ports:
            - "8100:8000"
        volumes:
            - ./payments:/app
        environment:
            SIGNING_KEY: 26373b9ea24f7e169e921f89ef4591046241eba5e6c30af3709cf6aa5a711b40
            DATABASE_URL: mongodb://root:password@mongo
            DATABASE_NAME: mongo-data
            WAIT_HOSTS: mongo:27017
    posts:
        build:
            context: ./posts
            dockerfile: ./Dockerfile.dev
        ports:
            - "8200:8000"
        volumes:
            - ./posts:/app
        environment:
            SIGNING_KEY: 26373b9ea24f7e169e921f89ef4591046241eba5e6c30af3709cf6aa5a711b40
            DATABASE_URL: mongodb://root:password@mongo
            DATABASE_NAME: mongo-data
            WAIT_HOSTS: mongo:27017
    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./ghi:/app
        ports:
            - "3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            REACT_APP_FASTAPI_accounts: http://localhost:8000
            REACT_APP_FastAPI_payments: http://localhost:8100
            REACT_APP_FastAPI_posts: http://localhost:8200